### ISSUE TITLE
Slow down/crash after several hours

### ISSUE THREAD

**Issue by joonazan** [MaxRobinsonTheGreat/LifeEngine#34] opened 2021-11-25 18:21 UTC
Performance decreases and memory use increases over time even though population does not. I assume that the plotting or something else just keeps accumulating data.

**Comment by xkortex** [comment] 2021-11-27 19:42
+1. Tried to run overnight and my tab had crashed. I observed about 1GB of bloat per hour of runtime. 

Not sure if this is a real effect or not, but it seemed like memory bloat increased faster when render was off, which would make sense if it were a data structure increasing in size and not a visible element leaking memory.

**Comment by MaxRobinsonTheGreat** [comment] 2021-11-28 18:50
Name changed since it isn't a memory leak (not possible in js), I believe it is caused by the fossil record tracking a progressively growing tree of ancestors. I will disable this and see if it fixes the bug.

**Comment by joonazan** [comment] 2021-11-30 12:32
I checked the code and as I suspected, all the graphs never discard data. They should remove every second entry after some amount of time has passed. I don't know if that is the biggest thing, though.

**Comment by joonazan** [comment] 2021-11-30 12:42
I think I've identified at least what grinds the simulation to a halt once it is already slow. `setInterval` keeps sheduling new updates even if the old ones haven't completed yet! See https://developer.mozilla.org/en-US/docs/Web/API/setInterval#ensure_that_execution_duration_is_shorter_than_interval_frequency

The correct way to do the timing would be to simulate a step and then sleep until the allocated time has passed. One could even separate rendering speed from simulation speed and time it with requestAnimationFrame.

**Comment by MaxRobinsonTheGreat** [comment] 2021-12-01 00:18
After disabling species tracking and running for ~24 hours there is no slow down or crash. This fix will be pushed to prod soon.

@joonazan Charts do discard data after 50k ticks. I'm pretty sure setInterval is not causing any issue, though on firefox it may be the reason for poor performance.

**Comment by joonazan** [comment] 2021-12-02 10:10
Well, setInterval definitely isn't the right choice for running expensive calculations. Would you be willing to merge if I wrote a version using setTimeout?

**Comment by MaxRobinsonTheGreat** [comment] 2021-12-02 14:52
You can do that, I imagine it would mitigate slow downs and potentially fix the firefox bug. 
If you do so, make sure to base your changes from the develop branch which has updated code, and I still want the syntactic sugar that setInterval provides for guaranteeing fixed interval execution. I also don't want the simulation and rendering to be separate intervals.

**Comment by MaxRobinsonTheGreat** [comment] 2021-12-03 00:52
@joonazan Just tried it out, changes are in the [reset-improvements branch](https://github.com/MaxRobinsonTheGreat/LifeEngine/tree/reset-improvements). I'm seeing performance issues, seems to slow down more than the `setInterval` implementation. May be a bug with my implementation, I'll keep playing around with it.

**Comment by joonazan** [comment] 2021-12-03 11:04
@MaxRobinsonTheGreat The branch still uses `setInterval`, it seems you didn't push those changes. I'll write an implementation now and you can compare then.

**Comment by joonazan** [comment] 2021-12-03 11:18
Why do you say that you don't want the simulation and rendering to be separate when that is already the case in the develop branch at least?

**Comment by MaxRobinsonTheGreat** [comment] 2021-12-04 05:50
Ah dammit I meant the [interval-improvements branch](https://github.com/MaxRobinsonTheGreat/LifeEngine/tree/interval-improvments). Looks like you implemented a similar thing, see my comment on that branch. Lets move this conversation there.

**Closed** 2021-12-17 23:54 UTC
Labels: bug
